language: node_js

node_js:
  - "stable"

sudo: false

before_script:
  - yarn install

branches:
  only:
  - master

jobs:
  include:
  - stage: build
    script: yarn build
  - # stage name not required, will continue to use `test`
  - stage: test
    script: yarn test

stages:
- build
- test


deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  local-dir: build